spring.application.name=marketplace

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/retrofit_marketplace
spring.datasource.username=lakshann
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server Configuration
# ===============================
server.port=8081